#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d          

bspc config border_width         2
bspc config window_gap          8
bspc config focused_border_color "#FFFFFF"
bspc config normal_border_color "#00000000" 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#autostart
polybar &
setxkbmap br &
picom --config /home/fudencio/.config/picom/picom.conf &
feh --bg-fill /home/fudencio/Pictures/wp3520914-legend-of-zelda-triforce-wallpaper.png &
xrandr --output HDMI-A-0 --mode 1360x768 &
cd .config/bspwm && ./script.sh
